#!/bin/bash
set -e

# NoctIS Manual Deployment Guide for noctis server
# This script provides step-by-step commands to deploy manually

REMOTE_USER="quantic"
REMOTE_HOST="noctis"
REMOTE_DIR="/home/quantic/NoctIS"

echo "🚀 NoctIS Deployment Guide for ${REMOTE_HOST}"
echo ""
echo "==============================================="
echo "Step 1: Copy files to noctis"
echo "==============================================="
echo "Run this command to copy the project:"
echo ""
echo "  scp -r /home/quantic/github/alkeis/NoctIS ${REMOTE_USER}@${REMOTE_HOST}:/home/quantic/"
echo ""
read -p "Press Enter when done..."

echo ""
echo "==============================================="
echo "Step 2: Connect to noctis and install Docker"
echo "==============================================="
echo "Run:"
echo "  ssh ${REMOTE_USER}@${REMOTE_HOST}"
echo ""
echo "Then execute these commands on noctis:"
echo ""
echo "# Install Docker"
echo "curl -fsSL https://get.docker.com -o get-docker.sh"
echo "sudo sh get-docker.sh"
echo "sudo usermod -aG docker \$USER"
echo ""
echo "# Create breaches directory if needed"
echo "mkdir -p /home/quantic/NoctIS/breaches"
echo ""
echo "# Build and start containers"
echo "cd /home/quantic/NoctIS"
echo "sudo docker compose -f docker-compose.prod.yml build"
echo "sudo docker compose -f docker-compose.prod.yml up -d"
echo ""
echo "# Check status"
echo "sudo docker compose -f docker-compose.prod.yml ps"
echo ""
echo "==============================================="
echo "🌐 Application will be available at: http://noctis"
echo "==============================================="
