"""Typesense service for indexing and searching OSINT data"""
import typesense
from typesense.exceptions import ObjectNotFound, TypesenseClientError
from typing import Optional, Dict, List, Any
import logging
from app.config import settings

logger = logging.getLogger(__name__)


class TypesenseService:
    """Service for managing Typesense collections and search operations"""

    def __init__(self):
        """Initialize Typesense client"""
        self._client: Optional[typesense.Client] = None
        self._initialized = False

    @property
    def client(self) -> typesense.Client:
        """Get or create Typesense client (lazy initialization)"""
        if self._client is None:
            self._client = typesense.Client({
                'api_key': settings.typesense_api_key,
                'nodes': [{
                    'host': settings.typesense_host,
                    'port': settings.typesense_port,
                    'protocol': settings.typesense_protocol
                }],
                'connection_timeout_seconds': settings.typesense_connection_timeout
            })
        return self._client

    async def health_check(self) -> Dict[str, Any]:
        """Check Typesense server health"""
        try:
            health = self.client.operations.perform('GET', '/health')
            # Typesense returns {"ok": true}
            if isinstance(health, dict) and health.get('ok'):
                return {"status": "healthy", "typesense": "ok"}
            elif isinstance(health, str) and health == 'ok':
                return {"status": "healthy", "typesense": "ok"}
            return {"status": "healthy", "details": health}
        except Exception as e:
            logger.error(f"Typesense health check failed: {e}")
            return {"status": "unhealthy", "error": str(e)}

    async def initialize_collections(self) -> Dict[str, bool]:
        """Initialize required collections if they don't exist"""
        results = {}

        # Silver Data: Raw imports (immutable, source of truth)
        silver_schema = {
            'name': 'silver_records',
            'enable_nested_fields': True,
            'fields': [
                # Unique identifier for this raw record
                {'name': 'id', 'type': 'string', 'index': True},  # Auto-generated by Typesense
                {'name': 'source_id', 'type': 'string', 'index': True},  # <breach>_<file>_<row_hash>

                # Core identifiers
                {'name': 'email', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'username', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'password', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'password_hash', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'phone', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'ip_address', 'type': 'string', 'optional': True, 'index': True},

                # Personal info
                {'name': 'full_name', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'first_name', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'last_name', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'gender', 'type': 'string', 'optional': True, 'facet': True},
                {'name': 'birth_date', 'type': 'string', 'optional': True, 'index': True},

                # Location info
                {'name': 'address', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'city', 'type': 'string', 'optional': True, 'facet': True, 'index': True},
                {'name': 'country', 'type': 'string', 'optional': True, 'facet': True, 'index': True},
                {'name': 'zip_code', 'type': 'string', 'optional': True, 'index': True},

                # Professional info
                {'name': 'company', 'type': 'string', 'optional': True, 'facet': True, 'index': True},
                {'name': 'job_title', 'type': 'string', 'optional': True, 'index': True},

                # Online presence
                {'name': 'social_media', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'website', 'type': 'string', 'optional': True, 'index': True},

                # Additional
                {'name': 'notes', 'type': 'string', 'optional': True, 'index': True},

                # Source metadata (immutable)
                {'name': 'breach_name', 'type': 'string', 'facet': True, 'index': True},
                {'name': 'breach_date', 'type': 'int64', 'optional': True, 'facet': True},
                {'name': 'source_file', 'type': 'string', 'facet': True, 'index': True},
                {'name': 'domain', 'type': 'string', 'optional': True, 'facet': True, 'index': True},
                {'name': 'imported_at', 'type': 'int64', 'index': True},

                # MDM linkage
                {'name': 'master_id', 'type': 'string', 'optional': True, 'index': True},  # Link to master record
            ],
            'default_sorting_field': 'imported_at'
        }

        # Master Data: Consolidated entities (deduplicated)
        master_schema = {
            'name': 'master_records',
            'enable_nested_fields': True,
            'fields': [
                # Master unique ID
                {'name': 'id', 'type': 'string', 'index': True},  # UUID or generated ID

                # MDM metadata
                {'name': 'status', 'type': 'string', 'facet': True, 'index': True},  # silver / golden
                {'name': 'confidence_score', 'type': 'float', 'index': True},  # 0-100
                {'name': 'created_at', 'type': 'int64', 'index': True},
                {'name': 'updated_at', 'type': 'int64', 'index': True},
                {'name': 'validated_by', 'type': 'string', 'optional': True, 'index': True},  # user/auto

                # Matching keys (for deduplication)
                {'name': 'matching_keys', 'type': 'string[]', 'facet': True},  # email, phone+name, etc.

                # Silver sources linked to this master
                {'name': 'silver_ids', 'type': 'string[]', 'index': True},
                {'name': 'source_count', 'type': 'int32', 'facet': True},  # Number of sources

                # Consolidated data (best values from all sources)
                {'name': 'email', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'email_verified', 'type': 'bool', 'optional': True},
                {'name': 'username', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'phone', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'phone_verified', 'type': 'bool', 'optional': True},
                {'name': 'ip_address', 'type': 'string', 'optional': True, 'index': True},

                # Personal info (consolidated)
                {'name': 'full_name', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'first_name', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'last_name', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'gender', 'type': 'string', 'optional': True, 'facet': True},
                {'name': 'birth_date', 'type': 'string', 'optional': True, 'index': True},

                # Location info (most recent or common)
                {'name': 'address', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'city', 'type': 'string', 'optional': True, 'facet': True, 'index': True},
                {'name': 'country', 'type': 'string', 'optional': True, 'facet': True, 'index': True},
                {'name': 'zip_code', 'type': 'string', 'optional': True, 'index': True},

                # Professional info
                {'name': 'company', 'type': 'string', 'optional': True, 'facet': True, 'index': True},
                {'name': 'job_title', 'type': 'string', 'optional': True, 'index': True},

                # Online presence
                {'name': 'social_media', 'type': 'string', 'optional': True, 'index': True},
                {'name': 'website', 'type': 'string', 'optional': True, 'index': True},

                # Aggregated breach info
                {'name': 'breach_names', 'type': 'string[]', 'facet': True},  # All breaches
                {'name': 'first_seen', 'type': 'int64', 'index': True},
                {'name': 'last_seen', 'type': 'int64', 'index': True},

                # Passwords found across sources
                {'name': 'passwords', 'type': 'string[]', 'optional': True},
                {'name': 'password_hashes', 'type': 'string[]', 'optional': True},
            ],
            'default_sorting_field': 'updated_at'
        }

        # Conflicts: Store field-level conflicts for manual resolution
        conflicts_schema = {
            'name': 'conflicts',
            'enable_nested_fields': True,
            'fields': [
                {'name': 'id', 'type': 'string', 'index': True},  # UUID
                {'name': 'master_id', 'type': 'string', 'index': True},  # Master record with conflict
                {'name': 'field_name', 'type': 'string', 'facet': True, 'index': True},  # Conflicting field
                {'name': 'status', 'type': 'string', 'facet': True, 'index': True},  # pending / resolved / ignored

                # Conflict details
                {'name': 'existing_value', 'type': 'string', 'optional': True},  # Current value in master
                {'name': 'new_value', 'type': 'string', 'optional': True},  # New value from silver
                {'name': 'existing_source', 'type': 'string', 'optional': True},  # Breach name of existing value
                {'name': 'new_source', 'type': 'string', 'optional': True},  # Breach name of new value

                # Resolution
                {'name': 'resolved_value', 'type': 'string', 'optional': True},  # Value chosen after resolution
                {'name': 'resolved_by', 'type': 'string', 'optional': True},  # user / auto
                {'name': 'resolved_at', 'type': 'int64', 'optional': True},

                # Metadata
                {'name': 'created_at', 'type': 'int64', 'index': True},
                {'name': 'silver_id', 'type': 'string', 'index': True},  # New silver record causing conflict
            ],
            'default_sorting_field': 'created_at'
        }

        results['silver_records'] = await self._ensure_collection(silver_schema)
        results['master_records'] = await self._ensure_collection(master_schema)
        results['conflicts'] = await self._ensure_collection(conflicts_schema)

        self._initialized = True
        return results

    async def _ensure_collection(self, schema: Dict[str, Any]) -> bool:
        """Ensure a collection exists, create if it doesn't"""
        try:
            # Check if collection exists
            self.client.collections[schema['name']].retrieve()
            logger.info(f"Collection '{schema['name']}' already exists")
            return True
        except ObjectNotFound:
            # Create collection
            try:
                self.client.collections.create(schema)
                logger.info(f"Collection '{schema['name']}' created successfully")
                return True
            except TypesenseClientError as e:
                logger.error(f"Failed to create collection '{schema['name']}': {e}")
                return False
        except Exception as e:
            logger.error(f"Error checking collection '{schema['name']}': {e}")
            return False

    async def get_collection_stats(self, collection_name: str = 'leaks') -> Optional[Dict[str, Any]]:
        """Get statistics for a collection"""
        try:
            collection = self.client.collections[collection_name].retrieve()
            return {
                'name': collection['name'],
                'num_documents': collection['num_documents'],
                'created_at': collection.get('created_at'),
                'num_memory_shards': collection.get('num_memory_shards', 0),
            }
        except ObjectNotFound:
            return None
        except Exception as e:
            logger.error(f"Error getting collection stats: {e}")
            return None

    async def search(
        self,
        query: str,
        search_fields: List[str],
        filter_by: Optional[str] = None,
        per_page: int = 20,
        page: int = 1,
        collection_name: str = 'leaks',
        typo_tolerance: bool = True,
        prefix: bool = True
    ) -> Dict[str, Any]:
        """
        Search in Typesense collection

        Args:
            query: Search query string
            search_fields: Fields to search in
            filter_by: Filter expression (e.g., "breach_name:=LinkedIn")
            per_page: Results per page
            page: Page number
            collection_name: Collection to search in
            typo_tolerance: Enable typo tolerance
            prefix: Enable prefix search

        Returns:
            Search results with hits and facets
        """
        try:
            search_params = {
                'q': query,
                'query_by': ','.join(search_fields),
                'per_page': per_page,
                'page': page,
                'typo_tokens_threshold': 1 if typo_tolerance else 0,
                'prefix': prefix,
            }

            if filter_by:
                search_params['filter_by'] = filter_by

            results = self.client.collections[collection_name].documents.search(search_params)

            return {
                'hits': results.get('hits', []),
                'found': results.get('found', 0),
                'out_of': results.get('out_of', 0),
                'page': page,
                'search_time_ms': results.get('search_time_ms', 0),
                'facet_counts': results.get('facet_counts', []),
            }

        except Exception as e:
            logger.error(f"Search error: {e}")
            return {
                'hits': [],
                'found': 0,
                'error': str(e)
            }

    async def multi_search(self, searches: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Execute multiple searches in a single request

        Args:
            searches: List of search parameters

        Returns:
            List of search results
        """
        try:
            search_requests = {
                'searches': [
                    {
                        'collection': search.get('collection', 'leaks'),
                        'q': search['query'],
                        'query_by': search['query_by'],
                        **{k: v for k, v in search.items() if k not in ['collection', 'query', 'query_by']}
                    }
                    for search in searches
                ]
            }

            results = self.client.multi_search.perform(search_requests, {})
            return results.get('results', [])

        except Exception as e:
            logger.error(f"Multi-search error: {e}")
            return []

    async def import_documents(
        self,
        documents: List[Dict[str, Any]],
        collection_name: str = 'leaks',
        action: str = 'upsert'
    ) -> Dict[str, Any]:
        """
        Import documents in batch

        Args:
            documents: List of documents to import
            collection_name: Target collection
            action: Import action (upsert, create, update)

        Returns:
            Import results with success/failure counts
        """
        if not documents:
            return {'success': 0, 'failed': 0, 'errors': []}

        try:
            # Import in batches
            results = self.client.collections[collection_name].documents.import_(
                documents,
                {'action': action}
            )

            # Parse results
            success_count = sum(1 for r in results if r.get('success', False))
            failed_count = len(results) - success_count
            errors = [r for r in results if not r.get('success', False)]

            return {
                'success': success_count,
                'failed': failed_count,
                'errors': errors[:10]  # Return first 10 errors
            }

        except Exception as e:
            logger.error(f"Import error: {e}")
            return {
                'success': 0,
                'failed': len(documents),
                'error': str(e)
            }

    async def delete_collection(self, collection_name: str) -> bool:
        """Delete a collection"""
        try:
            self.client.collections[collection_name].delete()
            logger.info(f"Collection '{collection_name}' deleted")
            return True
        except Exception as e:
            logger.error(f"Error deleting collection: {e}")
            return False

    async def get_facets(
        self,
        collection_name: str = 'leaks',
        facet_fields: List[str] = None
    ) -> Dict[str, List[Dict[str, Any]]]:
        """
        Get facet counts for specified fields

        Args:
            collection_name: Collection to query
            facet_fields: Fields to get facets for

        Returns:
            Dictionary of facet counts by field
        """
        if facet_fields is None:
            facet_fields = ['breach_name', 'domain', 'breach_date']

        try:
            search_params = {
                'q': '*',
                'query_by': 'email',
                'facet_by': ','.join(facet_fields),
                'per_page': 0,  # We only want facets, not results
            }

            results = self.client.collections[collection_name].documents.search(search_params)

            facets = {}
            for facet in results.get('facet_counts', []):
                field_name = facet['field_name']
                facets[field_name] = facet['counts']

            return facets

        except Exception as e:
            logger.error(f"Error getting facets: {e}")
            return {}


# Singleton instance
typesense_service = TypesenseService()
